import type { Metadata } from 'next';

import { BaseLayout } from '@/src/common/components/BaseLayout';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};
import '@/src/styles/index.css';

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="bg-blackM w-full">
                <BaseLayout>{children}</BaseLayout>
            </body>
        </html>
    );
}

