import type { Metadata } from 'next';
import {Rubik} from 'next/font/google';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};
import '@/src/styles/index.css';
export const roboto = Rubik({ subsets: ['latin'], weight: ['400'], style: 'normal' });

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${roboto.className} antialiased max-w-[1280px] my-0 mx-auto`}>{children}</body>
        </html>
    );
}

